name: Build RenPy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@v0.3.0
      with:
        version: "8.2.0"
        download_web: "yes"
    - name: Build RenPy
      uses: PaxlavaGames/renpy-web-build@v0.1.2
    - name: Show Web Build results
      run: ls web_build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './web_build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
